version: "3"

services:

  logstash:
    image: logstash:8.7.0
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/jar:/opt/
      - ./logstash/yml:/opt/yml/
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.7.0
    expose: # Exposes the default port 9200
      - 9200
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    volumes: # Stores elasticsearch data locally
      - ./elasticsearch/esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.7.0 
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Runs kibana service on default port 5601
      - 5601:5601
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  ems:
    build: 
      context: ./ems
      args:
        - USER_ARTIFACTORY=${USER_ARTIFACTORY}
        - KEY_ARTIFACTORY=${KEY_ARTIFACTORY}
    hostname: ems
    expose:
      - 7222
    ports:
      - 5959:7222
    

